version: "3"

services:
  meilisearch:
    image: ghcr.io/kunalsin9h/meilisearch:latest
    ports:
      - "7788:7700"
    restart: always
    deploy:
      mode: global
    volumes:
      - meili:/meilisearch/data.ms
    environment:
      MEILI_MASTER_KEY: "yWPFG870PyFQay84ec8OvudC7Nc4fjJdGV6D0BXkBhuzL4cqlOem2cf8pWGD+KsS
g0XYos+mdDi6l86nJ6hLvp="

volumes:
  meili:
    labels:
      - "a=b"
